### ISSUE TITLE
Unable to assume the service linked role when following the fargate tutorial

### ISSUE THREAD

**Issue by maltzj** [aws/amazon-ecs-cli#733] opened 2019-02-27 01:39 UTC
### Summary

I'm attempting to follow the Fargate deployment tutorial but I'm getting an error about being unable to assume a service linked role.

### Description

I'm attempting to follow the [ecs-cli Fargate deployment tutorial](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cli-tutorial-fargate.html) and have hit a problem attempting to deploy my service.

I am attempting to deploy my test container using `ecs-cli compose --project-name tutorial-maltz service up` but I am getting an error which says `"InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.\n\tstatus code: 400, request id`

So far I have created my IAM permission using the steps provided, and have verified that I have an IAM role `ecsTaskExecutionRole` which contains an `AmazonECSTaskExecutionRolePolicy`. This policy also has a trust relationship which looks like the following:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "Service": "ecs-tasks.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
All of this is being deployed off of a ecs-params.yml file which looks like the following:

* Which version of the CLI you are using? 1.2.1
* Which version of Go are you using? (Run: `go version`) go version go1.11.1 darwin/amd64
* What platform are you using to run ECS CLI commands? (E.g. Linux, MacOSX, Windows) osx

### Config files

* docker-compose.yml

```
version: '3'
services:
    wordpress:
        image: wordpress
        ports:
            - "80:80"
```

* ecs-params.yml

```
version: 1
task_definition:
    task_execution_role: ecsTaskExecutionRole
    ecs_network_mode: awsvpc
    task_size:
        mem_limit: 0.5GB
        cpu_limit: 256
run_params:
    network_configuration:
        awsvpc_configuration:
            subnets:
                - "subnet-from-ecs-cli-up"
            security_groups:
                - "subnet-created-by-ecs-cli-up"
        assign_public_ip: ENABLED
```

* ~/.ecs/config

```
version: v1
default: maltz-test-config
clusters:
  default:
    cluster: tutorial-maltz
    region: us-west-2
    default_launch_type: FARGATE
  maltz-test-config:
    cluster: tutorial-maltz
    region: us-west-2
    default_launch_type: FARGATE
  tutorial-maltz:
    cluster: tutorial-maltz
    region: us-west-2
    default_launch_type: FARGATE
```

### Expected Behavior

I'd expect that I can stand up my service

### Observed Behavior

```
INFO[0000] Using ECS task definition                     TaskDefinition="tutorial-maltz:3"
ERRO[0000] Error creating service                        error="InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.\n\tstatus code: 400, request id: 4a2969a9-3a30-11e9-a9dc-13c641ab2d7f" service=tutorial-maltz
INFO[0000] Created an ECS service                        service=tutorial-maltz taskDefinition="tutorial-maltz:3"
FATA[0000] InvalidParameterException: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
	status code: 400, request id: 4a2969a9-3a30-11e9-a9dc-13c641ab2d7f
```

**Comment by sarkis** [comment] 2019-02-27 03:26
The error `InvalidParameterException: Unable to assume the service linked role.` is referring to the service linked role: https://docs.aws.amazon.com/IAM/latest/UserGuide/using-service-linked-roles.html

This role needs to be created by the user. Once you create it, either via console or cli (directions in link above), the issue should resolve.

**Comment by allisaurus** [comment] 2019-03-07 20:23
Hi @maltzj - what @sarkis said is correct, the "Service linked role" is and account-wide role that is assumed by ECS to take actions on your behalf and is distinct from the `ecsTaskExecutionRole`. Please reference the above link and let us know if you're unblocked or continuing to have problems.

**Comment by sarkis** [comment] 2019-03-07 20:25
@allisaurus curious - is this something that should be mentioned in the AWS tutorial? https://docs.aws.amazon.com/AmazonECS/latest/developerguide/ecs-cli-tutorial-fargate.html

I'm wondering if this was an account issue (i.e. older account maybe needed to manually create the service linked role)? Would amazon-ecs-cli create this role if it had the proper perms?

**Comment by allisaurus** [comment] 2019-03-07 20:40
@sarkis good callout, I don't find any mention of it in the tutorial currently and it would be helpful to at least include a note re: why it's needed and a link to the [AWSServiceRoleForECS](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html) page. 

Typically, this role doesn't need to be manually created because [ECS tries to create it for you](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using-service-linked-roles.html#create-service-linked-role) automatically when creating a cluster or creating/updating a service that requires it. However, if your IAM user doesn't have permissions to create the role, automatic creation will fail, as it did above. 

Instructions on how to create this role and the permissions needed to do it are described in the above link.

**Comment by sarkis** [comment] 2019-03-07 20:41
> However, if your IAM user doesn't have permissions to create the role, automatic creation will fail, as it did above.
It all makes sense now - thank you @allisaurus for the explanation!

**Comment by allisaurus** [comment] 2019-03-08 18:39
Closing b/c confusion around "Service Linked Roles" seems to be cleared up. Feel free to reopen if further questions or issues crop up.

**Closed by allisaurus** 2019-03-08 18:39 UTC
Labels: Pending response

**Comment by markentingh** [comment] 2019-11-24 06:34
This is also happening to me. I have the role in place, generated in my cloudformation template:

```
"ECSTaskExecutionRole": {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "AssumeRolePolicyDocument": {
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "Service": [
                                    "ecs-tasks.amazonaws.com"
                                ]
                            },
                            "Action": [
                                "sts:AssumeRole"
                            ]
                        }
                    ]
                },
                "Path": "/",
                "Policies": [
                    {
                        "PolicyName": "AmazonECSTaskExecutionRolePolicy",
                        "PolicyDocument": {
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "ecr:GetAuthorizationToken",
                                        "ecr:BatchCheckLayerAvailability",
                                        "ecr:GetDownloadUrlForLayer",
                                        "ecr:BatchGetImage",
                                        "logs:CreateLogStream",
                                        "logs:PutLogEvents"
                                    ],
                                    "Resource": "*"
                                }
                            ]
                        }
                    }
                ]
            }
        }
```

and I am using`{"Ref": "ECSTaskExecutionRole"}` within the `ExecutionRoleArn` property for resource type `AWS::ECS::TaskDefinition`

**Comment by markentingh** [comment] 2019-11-24 06:51
Since I ran into this problem today and it took a few hours to figure out, I'll make it easy for everyone else who is having the same issue. Simply execute this command in your AWS CLI `aws iam create-service-linked-role --aws-service-name ecs.amazonaws.com`, then use the newly created role's **Arn** within the `ExecutionRoleArn` property of your `AWS::ECS::TaskDefinition`

**Comment by mazend** [comment] 2020-12-27 03:37
Hi. Here is my case.
I faced the same error:
`Invalid request provided: CreateService error: Unable to assume the service linked role. Please verify that the ECS service linked role exists. (Service: Ecs, Status Code: 400, Request ID: 521b7036-3b8c-4431-b304-2b804e057920, Extended Request ID: null)`

At first I thought the issue has something to do with the service linked role. However it seems AWS gives wrong information.
After investigating it I found out that the root case was that I gave wrong image path in `AWS::ECS::TaskDefinition` in stack template in CloudFormation:
`
          Image: !Sub ${DockerHubUsername}/${ServiceName}:${ServiceVersion}
`
So the CloudFormation failed to get the image in a row and failed to generate ECS(EC2, FARGATE) service.
It looks like AWS think the issue had something to do with linked service role but it wasn't.
**The root cause was that I provided wrong image path..**

**Comment by markotitel** [comment] 2020-12-27 22:54
@mazend Yes exactly the same issue I got into right now.
Unfortunately looks like error handling in this kind of situation is not soon to be updated. :(

**Comment by aprilmintacpineda** [comment] 2022-11-16 10:54
```
invalid request provided: Create Cluster Invalid Request: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
```

I encountered this error while using cloudformation with a profile that has admin access. The first run failed, then I simply rerun it again without changing anything at all, then it succeeded.

**Comment by alettaklopper2310** [comment] 2023-04-19 11:55
I encountered this problem as well when using Clouformation. For me, the fix was to add the ExecutionRole (custom role in same template) to the "DependsOn" option in the ECS Service config.

**Comment by kaunglvlv** [comment] 2023-05-13 16:41
> ```
> invalid request provided: Create Cluster Invalid Request: Unable to assume the service linked role. Please verify that the ECS service linked role exists.
> ```
> 
> I encountered this error while using cloudformation with a profile that has admin access. The first run failed, then I simply rerun it again without changing anything at all, then it succeeded.

Same here.  I was just trying to create an empty cluster.  Redeployed and it worked 😒
