### ISSUE TITLE
Allow ELB to be associated with ECS service upon creation

### ISSUE THREAD

**Issue by frewsxcv** [aws/amazon-ecs-cli#60] opened 2016-01-07 21:36 UTC
This is an option in the web UI, but not in `ecs-cli compose service`

**Comment by samuelkarp** [comment] 2016-01-08 05:49
Closing as this is a duplicate of https://github.com/aws/amazon-ecs-cli/issues/21.

**Closed by samuelkarp** 2016-01-08 05:49 UTC
