### ISSUE TITLE
Unsupported config option 'logging'

### ISSUE THREAD

**Issue by mattmccarty** [aws/amazon-ecs-cli#273] opened 2017-07-07 18:07 UTC
My docker-compose file is set to version 2 and I am attempting to use the awslogs driver using the logging.driver and logging.options parameters. When running 'ecs-cli compose create', I get an error "'logging' Unsupported config option for [service-name-here] server".

Here is my docker-compose file:

`
    version: '2'

    services:
        registrator:
            image     : ${AWS_ECR_HOST}/registrator:${AWS_ECR_IMG_TAG}
            command   : "-cleanup=true consul://X.X.X.X:8500"
            hostname  : "${AWS_ECS_CLUSTER}"
            privileged: true
            volumes:
                - /var/run/docker.sock:/tmp/docker.sock
            logging:
                driver : awslogs
                options:
                    awslogs-group        : "${AWS_ECS_CLUSTER}"
                    awslogs-region       : "us-east-1"
                    awslogs-stream-prefix: "registrator"
`

I have the following versions installed on my system:
Docker: Docker version 17.06.0-ce, build 02c1d87
Docker Compose: docker-compose version 1.14.0, build c7bdf9e
ECS CLI: ecs-cli version 0.6.0 (1053c82)

**Comment by yinshiua** [comment] 2017-07-07 19:22
@mattmccarty I was able to use the same compose file to run `ecs-cli compose create` and create a Task Definition successfully. Could it be unexpected characters in your environment variables?

**Comment by mattmccarty** [comment] 2017-07-07 20:13
Thanks for the response @yinshiua. I think I've found the issue...

I have two docker-compose files:

1. app/docker-compose.yml
2. app/service/registrator/docker-compose.yml

docker-compose.yml #2 extends the registrator service from the docker-compose.yml file #1 (which contains the logging parameter). If I add the logging parameter to docker-compose.yml #2 and *then* extend the rest of the service from docker-compose.yml #1, the task will get deployed.

**Comment by yinshiua** [comment] 2017-07-08 07:22
@mattmccarty Both of the examples you provided above worked for me. Can you help me understand what was the issue and what did you do to resolve this?

**Comment by mattmccarty** [comment] 2017-07-10 13:55
The ecs-cli compose create command would not except the 'logging' parameter when the docker-compose.yml file in question was extending a service from another docker-compose.yml file. Removing the 'logging' parameter from the 'parent' docker-compose.yml file and adding it to the 'child' docker-compose.yml file worked. At least this was the case in my environment.

I haven't had a chance to look at the ecs-cli code the performs this operation, so I'm not entirely sure why the work around fixed the issue.

**Comment by yinshiua** [comment] 2017-07-10 18:23
@mattmccarty Thanks for the explanation. I am still not able to reproduce this. I added `logging` in both the parent docker compose file and the child docker compose file, and I was still able to run `ecs-cli compose create` successfully. Here's what I have tested:

parent docker compose file (test.yml):
```
version: '2'
services:
  registrator:
    image     : myimage
    command   : "-cleanup=true consul://X.X.X.X:8500"
    privileged: true
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    logging: 
      driver : "awslogs"
      options:
         awslogs-group        : "${AWS_ECS_CLUSTER}"
         awslogs-region       : "us-east-1"
         awslogs-stream-prefix: "registrator"
```

child docker compose file (test-us-west-2.yml):
```
version: '2'
services:
    registrator:
        logging:
            driver : "awslogs"
            options:
                awslogs-group        : "${AWS_ECS_CLUSTER}"
                awslogs-region       : "us-west-2"
                awslogs-stream-prefix: "registrator"
        extends:
            file   : test.yml
            service: registrator
```

**Comment by mattmccarty** [comment] 2017-07-11 20:40
Really strange. Ok thank you for the assist. I think we can close this as a non-issue. It must have been environment specific.

**Comment by yinshiua** [comment] 2017-07-11 23:41
Ok, I'll close this issue for now. Please reopen this if similar issue occurs.

**Closed by yinshiua** 2017-07-11 23:41 UTC
Labels: Pending response
