### ISSUE TITLE
log_driver during compose

### ISSUE THREAD

**Issue by mkoppanen** [aws/amazon-ecs-cli#162] opened 2016-10-05 12:49 UTC
Am I missing something or is log_driver and log_opt dropped from the output? Running with following yaml file:

```
version: '2'
services:
  web:
    image: amazon/amazon-ecs-sample
    ports:
     - "80:80"
    log_driver: awslogs
    log_opt:
     aws-region: us-west-2
```

Produces following output (ecs-cli compose -f <file> --debug up):

```
  ContainerDefinitions: [{
      Command: [],
      Cpu: 0,
      DnsSearchDomains: [],
      DnsServers: [],
      DockerLabels: {

      },
      DockerSecurityOptions: [],
      EntryPoint: [],
      Environment: [],
      ExtraHosts: [],
      Image: "amazon/amazon-ecs-sample",
      Links: [],
      Memory: 512,
      MountPoints: [],
      Name: "web",
      PortMappings: [{
          ContainerPort: 80,
          HostPort: 80,
          Protocol: "tcp"
        }],
      Privileged: false,
      ReadonlyRootFilesystem: false,
      Ulimits: [],
      VolumesFrom: []
    }],
  Family: "ecs-cli-test",
  Volumes: []
}
```

**Comment by yinshiua** [comment] 2016-10-14 23:04
Version 2 file format no longer accepts `log_driver` and `log_opt`. See https://docs.docker.com/compose/compose-file/#/logging for reference.

We are working on better error handling. (Pending release)

**Comment by mtomas** [comment] 2016-11-15 14:14
any updates on this ?

**Comment by uttarasridhar** [comment] 2017-01-06 20:09
Released in https://github.com/aws/amazon-ecs-cli/releases/tag/v0.4.5

**Closed** 2017-01-06 20:09 UTC
Labels: pending release

**Comment by garthk** [comment] 2017-04-26 00:10
For those coming here via Google in early-mid 2017:

Contrary to @yinshiua's advice above, the `docker-compose.yml` version 2 format does accept `log_driver` and `log_opt`. It's version 3 that replaces them with `logging.driver` and `logging.options`.

Contrary to the [ECS CLI tutorial](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_tutorial.html#ECS_CLI_tutorial_compose_create), which as of writing says…

> At this time, the Amazon ECS CLI supports Docker compose file syntax versions 1 and 2.
>
> The following parameters are supported in compose files for the Amazon ECS CLI:
> …
> * `log_driver`
> * `log_opt`

… it's actually version 3 that `ecs-cli` 0.5.0 supports, with `logging.driver` and `logging.options`. Try, for example:

```yaml
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-2
        awslogs-group: awslogs-containers-dev
```

**Comment by nrdlngr** [comment] 2017-06-02 22:29
The [Docker documentation for Compose version 2](https://docs.docker.com/compose/compose-file/compose-file-v2/#logging) does not list `log_driver` or `log_opt` as valid options.

The `docker-compose` CLI also does not accept them for version 2:
```
acbc3284a481:test ericn$ cat docker-compose.yml
version: '2'
services:
  web:
    image: amazon/amazon-ecs-sample
    ports:
     - "80:80"
    log_driver: awslogs
    log_opt:
     aws-region: us-west-2
acbc3284a481:test ericn$ docker-compose up
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.web: 'log_opt'
```
The `logging` option syntax for version 2 and 3 seems to be identical in the Docker docs.

At the time of this writing, the ECS CLI only supports versions 1 and 2 of Compose files. I'll update the ECS CLI documentation to show the different logging syntax for versions 1 and 2.

**Comment by garthk** [comment] 2017-06-03 00:17
Gaah. I went over that three times to be sure; wish I'd screen capped it.

Confirming: `logging` is in `docker-compose` 2 and 3. And, I'm now wondering whether the root cause here was a missing or ignored `version. Thanks for digging in and clarifying the docs.
