### ISSUE TITLE
Running ecs-cli up returns 'panic: runtime error: invalid memory address or nil pointer dereference'

### ISSUE THREAD

**Issue by dgonzo** [aws/amazon-ecs-cli#111] opened 2016-04-30 15:05 UTC
I had difficulty getting ecs-cli to "down" a cluster and cloudformation. Ultimately, I removed the elements that weren't terminating properly. Now when I try an use ecs-cli up to create a new cluster I get:

```
(ptk) MacBook-Pro:coral gonzo$ ecs-cli up --keypair ecs_ptk --capability-iam --size 1 --instance-type m4.xlarge
ecs-cli up --keypair ecs_ptk --capability-iam --size 1 --instance-type m4.large
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x2f0545]

goroutine 1 [running]:
github.com/aws/aws-sdk-go/aws/ec2metadata.(*EC2Metadata).GetMetadata(0x0, 0x6e9650, 0x19, 0x0, 0x0, 0x0, 0x0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/ec2metadata/api.go:24 +0x1b5
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.requestCredList(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:133 +0x85
github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds.(*EC2RoleProvider).Retrieve(0xc20803bb90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/ec2rolecreds/ec2_role_provider.go:89 +0x61
github.com/aws/aws-sdk-go/aws/credentials.(*ChainProvider).Retrieve(0xc20803bbc0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/chain_provider.go:75 +0xfc
github.com/aws/aws-sdk-go/aws/credentials.(*Credentials).Get(0xc208066300, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/aws/aws-sdk-go/aws/credentials/credentials.go:185 +0xf0
github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.(*CliConfig).ToServiceConfig(0xc2080560a8, 0x67f110, 0x0, 0x0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/config.go:68 +0x274
github.com/aws/amazon-ecs-cli/ecs-cli/modules/config.NewCliParams(0xc2080b80f0, 0xb285e8, 0xc208031470, 0x69a2b0, 0x0, 0x0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/config/params.go:63 +0x3a8
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.func·001(0xc2080b80f0, 0xb285e8, 0xc208031470, 0xdc1b, 0x0, 0x0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:174 +0x4e
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.createCluster(0xc2080b80f0, 0xb285e8, 0xc208031470, 0xb284b0, 0xc20801f0c0, 0xb28560, 0xc20803bb00, 0xb285c0, 0xc2080560a0, 0x0, ...)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:117 +0x1b7
github.com/aws/amazon-ecs-cli/ecs-cli/modules/command.ClusterUp(0xc2080b80f0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/modules/command/cluster_app.go:60 +0x36e
github.com/codegangsta/cli.(*App).RunAsSubcommand(0xc208080400, 0xc2080b8000, 0x0, 0x0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/codegangsta/cli/app.go:262 +0xd9a
github.com/codegangsta/cli.Command.startApp(0x681390, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7d8c50, 0x6c, 0x0, ...)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/codegangsta/cli/command.go:199 +0x7e7
github.com/codegangsta/cli.Command.Run(0x681390, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x7d8c50, 0x6c, 0x0, ...)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/codegangsta/cli/command.go:55 +0x14a8
github.com/codegangsta/cli.(*App).Run(0xc208080200, 0xc20800a000, 0x9, 0x9, 0x0, 0x0)
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/vendor/src/github.com/codegangsta/cli/app.go:159 +0xd7b
main.main()
        /usr/src/app/src/github.com/aws/amazon-ecs-cli/ecs-cli/main.go:45 +0x946
```

**Comment by hobofan** [comment] 2016-06-06 10:21
Looks like a duplicate of #105

**Comment by uttarasridhar** [comment] 2016-06-29 18:12
Thanks for reporting the bug and apologies for the delay in the fix.
Released in https://github.com/aws/amazon-ecs-cli/releases/tag/v0.3.1

**Closed by uttarasridhar** 2016-06-29 18:12 UTC
