### ISSUE TITLE
Variable substitution

### ISSUE THREAD

**Issue by miticojo** [aws/amazon-ecs-cli#42] opened 2015-11-24 06:38 UTC
I used to use variables substitution in my docker-compose file, but it seems that ecs-cli doesn't recognise them:
```
db:
  image: "postgres:${POSTGRES_VERSION}"
```
I'd like to use it with my CI tool in order to apply different variable for different stages. 

With latest version I got:

>ERRO[0000] Error registering task definition             error=ClientException: Container.image contains invalid characters.
	status code: 400, request id: ******* family=0xc20808e2c0
> ERRO[0000] Create task definition failed                 error=ClientException: Container.image contains invalid characters.
	status code: 400, request id: ********

Ref: https://docs.docker.com/compose/compose-file/#variable-substitution

Thanks,
Giorgio

**Comment by uttarasridhar** [comment] 2015-11-24 06:39
Duplicate of #28

**Comment by miticojo** [comment] 2015-11-25 06:14
Unfortunately I don't speak Go language at the moment and, while waiting for implementation, I've created a small  utility that solve that need: https://github.com/miticojo/ecs-cli-vars

**Comment by uttarasridhar** [comment] 2016-04-12 21:15
tracking it in #28

**Closed by uttarasridhar** 2016-04-12 21:15 UTC
Labels: enhancement

**Comment by andrykonchin** [comment] 2018-06-22 16:15
Could anybody provide me an example? I can't set it to work.

I run following command to create service:

```
DOCKER_IMAGE_TAG=9105d31 --file ecs-cli.docker-compose.yml ecs-cli compose service up
```

I try to use environment variable substitution in the following way (in docker-compose file):

```
services:
  api:
    image: "...-api:${DOCKER_IMAGE_TAG}"
```

The task fails to run with following error message (in AWS console UI)
`STOPPED (CannotPullContainerError: API error (404): manifes)`

 and I can an image name in UI - `494674277282.dkr.ecr.eu-west-1.amazonaws.com/resolver-local-api:` (without a tag)

Does it mean I do something wrong or the feature is broken?
