### ISSUE TITLE
Feature request: make compose prefixes configurable by argument or environment variable

### ISSUE THREAD

**Issue by etsuo** [aws/amazon-ecs-cli#333] opened 2017-10-10 21:22 UTC
There's a default prefix that gets attached to projects and services that can be disabled in `~/.ecs/config` using the `compose-project-name-prefix` and `compose-service-name-prefix` entries. Unfortunately, this forces us to create a config file where we otherwise wouldn't need to, which makes it harder for us to create generic automation scripts that we can use across our various projects and clients.

Request: please make `compose-project-name-prefix` and `compose-service-name-prefix` command line arguments and / or environment variables that override the behavior.

**Comment by PettitWesley** [comment] 2017-10-10 22:38
@etsuo, thanks for the question. We understand the annoyances caused by the way that the prefixes and configuration file currently works. We are currently in the final stages of implementing a solution to this!

Please see the proposal on deprecating the prefixes: #252 
You can track our work implementing that here: #313 

In addition, we have implemented the functionality described [here](https://github.com/aws/amazon-ecs-cli/blob/master/proposals/multi-cluster-config.md) to support multiple configurations (both for creds and clusters). This functionality has not been merged into master yet, nor has it been released- but it will be soon!

Furthermore, we do already have a flag, '--project-name' (env var: $COMPOSE_PROJECT_NAME) which allows you to set the project name. We do not have a flag for the `compose-service-name-prefix`, nor do we have any plans to add one. We think that the functionality laid out in #252 alleviates the need for a flag. Let us know if you disagree!

**Comment by PettitWesley** [comment] 2017-12-05 23:42
Deprecation of the prefixes was released in `v1.0.0`

**Closed** 2017-12-05 23:41 UTC
Labels: Feature request, Pending push
