### ISSUE TITLE
Task Placement Strategy should be exposed via ecs-cli 

### ISSUE THREAD

**Issue by 85matthew** [aws/amazon-ecs-cli#515] opened 2018-05-23 21:09 UTC
### Summary
Task Placement Strategy should be exposed to ecs-cli: 

Specifically the default method (random) is not sufficient for production applications. We would like the ability to specify how tasks get allocated (most importantly "spread" by availability zone & also by CPU or Memory allocation strategies)

### Description
Default placementStrategy (random) is not sufficient for production applications. Would like the ability to specify how tasks get allocated (most importantly "spread" across availability zone & also by CPU or Memory allocation strategies)

Would like to create a new command line flag to pass in a valid placementStrategy

### Expected Behavior
Tasks created via ecs-cli should be able to specify an alternative placementStrategy

Proposing creation of a "placement-strategy" flag that would be passed something like this:

"--placement-strategy spread/attribute:ecs.availability-zone,binpack/memory"

Which would place tasks in different availability zones & place on node with minimum memory (meeting requirement of application)

(comma separated strategies, with forward slash separated "Type|Field" values.

**Comment by SoManyHs** [comment] 2018-05-25 21:30
Hi @85matthew,
Thanks for opening this issue! This is a duplicate of https://github.com/aws/amazon-ecs-cli/issues/212. We currently have plans to integrate support for task placement strategies in the CLI. I see you already opened a [PR](https://github.com/aws/amazon-ecs-cli/pull/518) for this -- generally for feature requests, we like to have a conversation about the design before accepting PRs (See our [contributing doc](https://github.com/aws/amazon-ecs-cli/blob/master/CONTRIBUTING.md#contributing-code) for more details).

**Comment by 85matthew** [comment] 2018-05-30 19:04
Ah... Okay. Sorry about that. Didn't know if this was enough work to
warrant a design. Also thought the other request (#212) was slightly
different since it said task placement constraints as opposed to task
placement strategy (but they may have meant both).

Let me know if there's anything else I can help with. Just submitted the
license agreement as well. Thanks!
Matt

**Comment by brandonshough** [comment] 2018-08-08 20:56
Any updates on this?

**Comment by SoManyHs** [comment] 2018-09-10 17:44
This is now available in 1.7.0. Closing.

**Closed by SoManyHs** 2018-09-10 17:44 UTC
Labels: Feature request, PR

**Comment by dimisjim** [comment] 2019-05-15 07:25
@SoManyHs Is updating existing services' placements strategies impossible due to API constraints? I see from `compose service` doc (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-service.html), it's only possible to modify services that were brought up with ecs-cli only. Is this a limitation due to https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateService.html

Is there a way to add a placement strategy on preexisting services with ecs-cli (or any other tool for that matter)?
