### ISSUE TITLE
ecs-cli apparently doesn't support af-south-1 region?

### ISSUE THREAD

**Issue by elbow** [aws/amazon-ecs-cli#1016] opened 2020-04-28 18:52 UTC
#### Summary

I am unable to use ecs-cli to build a cluster in af-south-1.  It always complains thusly:

```
FATA[0002] Error executing 'up': ValidationError: Parameter EcsInstanceType failed to satisfy constraint: must be a valid EC2 instance type.
```
m5.xlarge is a valid instance type according to:

```
aws ec2 describe-instance-type-offerings --region af-south-1
```

#### Description

executed `ecs-cli up --region af-south-1 --keypair steve --capability-iam  --instance-type m5.xlarge --cluster cpt-conf-telviva-com --launch-type EC2 --size 2`

ecs-cli version `aws-cli/2.0.10 Python/3.7.3 Linux/4.15.0-91-generic botocore/2.0.0dev14` - installed right now

On linux

#### Expected Behavior

cluster created, as it in when I build in on eu-west-2.

#### Observed Behavior

```
steve@ct-vid01:~/jitsi/docker-jitsi-meet/deploy/cpt-conf-telviva-com$ ecs-cli up --region af-south-1 --keypair steve --capability-iam  --instance-type m5.xlarge --cluster cpt-conf-telviva-com --launch-type EC2 --size 2
INFO[0001] Using recommended Amazon Linux 2 AMI with ECS Agent 1.39.0 and Docker version 18.09.9-ce
INFO[0001] Created cluster                               cluster=cpt-conf-telviva-com region=af-south-1
FATA[0002] Error executing 'up': ValidationError: Parameter EcsInstanceType failed to satisfy constraint: must be a valid EC2 instance type.
	status code: 400, request id: 65fbdda4-5b40-4da9-8c72-720fcad7083e
```

Same command on eu-west-2:

```
steve@ct-vid01:~/jitsi/docker-jitsi-meet/deploy/cpt-conf-telviva-com$ ecs-cli up --region eu-west-2 --keypair steve --capability-iam  --instance-type m5.xlarge --cluster cpt-conf-telviva-com --launch-type EC2 --size 2
INFO[0001] Using recommended Amazon Linux 2 AMI with ECS Agent 1.39.0 and Docker version 18.09.9-ce
INFO[0002] Created cluster                               cluster=cpt-conf-telviva-com region=eu-west-2
INFO[0004] Waiting for your cluster resources to be created...
INFO[0004] Cloudformation stack status                   stackStatus=CREATE_IN_PROGRESS
```

**Comment by elbow** [comment] 2020-04-28 19:11
Looks like I've also got this problem - https://github.com/aws/amazon-ecs-cli/issues/1006

af-south-1 does not have t2.micro  -- it does have t3.micro

**Comment by elbow** [comment] 2020-04-28 19:28
Yes, definitely the same problem - I changed the default instance type to t3.micro and rebuild ecs-cli and I can bring my cluster up.

**Comment by allisaurus** [comment] 2020-05-19 22:42
Closing as a duplicate of https://github.com/aws/amazon-ecs-cli/issues/1006 which was addressed by https://github.com/aws/amazon-ecs-cli/pull/1007

**Closed by allisaurus** 2020-05-19 22:42 UTC
