### ISSUE TITLE
ecs-cli local up cannot read from parameter store when forward slashes exist in parameter name

### ISSUE THREAD

**Issue by ndavies-om1** [aws/amazon-ecs-cli#933] opened 2019-09-27 14:14 UTC
#### Summary
ecs-cli local up cannot read from parameter store when forward slashes exist in parameter name

#### Description
Using command `ecs-cli local up --task-def-compose docker-compose.ecs-local.yml --override docker-compose.ecs-local.override.yml`

ecs-cli version 1.16.0

go version go1.13 darwin/amd64

macOS

#### Config files
* docker-compose.yml
```
version: "3.4"
services:
  onoff:
    command:
      - ./myapp
    environment:
      AWS_CONTAINER_CREDENTIALS_RELATIVE_URI: /creds
      AWS_REGION: us-east-1
      AWS_SDK_LOAD_CONFIG: "1"
      MY_SECRET: ${myapp_MY_SECRET}
      ECS_CONTAINER_METADATA_URI: http://169.254.170.2/v3
    image: myapp
    labels:
      ecs-local.secret.BOT_TOKEN: arn:aws:ssm:us-east-1:<myaccount>:parameter/a/b/c/my_secret
      ecs-local.task-definition-input.type: local
      ecs-local.task-definition-input.value: xxxxx/task-definition.json
    logging:
      driver: awslogs
      options:
        awslogs-group: ecs
        awslogs-region: us-east-1
        awslogs-stream-prefix: myapp
    networks:
      ecs-local-network: null
    ports:
      - 3000:3000

networks:
  ecs-local-network:
    external: true
```
* ecs-params.yml

* ~/.ecs/config

#### Observed Behavior
```
INFO[0000] The network ecs-local-network already exists 
INFO[0000] The amazon-ecs-local-container-endpoints container already exists with ID 934e9acd68cbf45d1a1c3589e5d80ce626910e5a8f2fb249e399708e7584594a 
INFO[0000] Started container with ID 934e9acd68cbf45d1a1c3589e5d80ce626910e5a8f2fb249e399708e7584594a 
FATA[0000] Failed to decrypt secret due to 
failed to retrieve decrypted secret from arn:aws:ssm:us-east-1:<myaccount>:parameter/a/b/c/my_secret due to ParameterNotFound: 
	status code: 400, request id: 1bbf17c3-8558-492f-b5a5-338b34bea5d5: ParameterNotFound: 
	status code: 400, request id: 1bbf17c3-8558-492f-b5a5-338b34bea5d5 

```

Closer inspection of the code reveals that the DecryptSecret function in `ecs-cli/modules/cli/local/secrets/clients/clients.go` is the problem. It splits the string on a forward slash and combines without the forward slash to get the param name. Replacing:
`paramName = strings.Join(resource[1:], "")`
with
`paramName = "/" + strings.Join(resource[1:], "/")`
seems to solve the problem. I am a terrible at Go, so there is probably a better way of fixing this.

**Comment by gomex** [comment] 2019-11-29 20:35
Any news? I am facing this problem.

**Comment by hencrice** [comment] 2019-11-29 20:37
Hey gomex, we have merged the fix and it should be available in the latest release.

**Comment by gomex** [comment] 2019-11-29 20:39
Can you please confirm the version number of this release?

**Comment by hencrice** [comment] 2019-11-29 20:43
Hmm that is indeed the latest version. Would you mind opening a new issue documenting the symptoms? I suspect it might not be the exact same problem that was fixed here (Or it could be just that the fix was not comprehensive enough). Thanks!

**Comment by gomex** [comment] 2019-11-29 20:44
Here is my error:

```
FATA[0000] Failed to decrypt secret due to 
failed to retrieve decrypted secret from arn:aws:ssm:us-east-1:666631661947:parameter/staging/app_name/my_api_secret_key due to ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
        status code: 400, request id: 9165ba83-10ba-4a3c-9444-3fdce624bc98: ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
        status code: 400, request id: 9165ba83-10ba-4a3c-9444-3fdce624bc98 
```

**Comment by hencrice** [comment] 2019-11-29 20:53
Hey gomex, your error seems to be different from the original issue we fixed.

Yours says `ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive)......` while the original error said `ParameterNotFound`.

Could you confirm that your parameter name satisfies the constraints documented on https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-parameter-name-constraints.html ?

**Comment by gomex** [comment] 2019-11-29 20:54
I am using this parameter on my ECS... running on fargate :(

**Comment by hencrice** [comment] 2019-11-29 21:00
Hey gomex,

To better help us diagnose the cause, could you open a new issue documenting the steps to reproduce the symptoms you are observing? Thanks

**Closed** 2019-12-10 19:43 UTC
Labels: Bug, Pending release
