### ISSUE TITLE
Running Locally using SSM Parameters with a Hierarchy

### ISSUE THREAD

**Issue by Aubtin** [aws/amazon-ecs-cli#1010] opened 2020-04-12 22:12 UTC
#### Summary

Running the task locally while using SSM parameters causes an error when the parameter contains `/aws/` anywhere within the name. The documentation only mentions that `aws` and `ssm` cannot prefix the name. In the example below it fails, but removing `aws` from the hierarchy fixes the issue.

Additionally the error message seems to be incorrect.
#### Description

* Command: `ecs-cli local up --task-def-remote ${TASK}`
* ecs-cli version: `ecs-cli version 1.18.1 (7e9df84)`
* Go version: `go version go1.14.1 darwin/amd64`
* Platform: `macOS 10.15.3`

#### Expected Behavior
Successfully build the image and run locally including the parameters from the parameter store.
#### Observed Behavior
```
INFO[0002] Reading task definition from ${TASK}:11
 
INFO[0002] Task Definition network mode is ignored when running containers locally. Tasks will be run in the ecs-local-network.  networkMode=awsvpc
WARN[0002] awslogs log driver is ignored when running locally. Tasks will default to json-file instead. This can be changed in your compose override file. 
INFO[0002] Successfully wrote docker-compose.ecs-local.yml 
INFO[0002] Successfully wrote docker-compose.ecs-local.override.yml 
INFO[0002] The network ecs-local-network already exists 
INFO[0002] The amazon-ecs-local-container-endpoints container already exists with ID 3a90c70b7775c0c2e34b6c1a3c8ce3d5dd4063c2d5c4413c9455c329d44e674e 
INFO[0002] Started container with ID 3a90c70b7775c0c2e34b6c1a3c8ce3d5dd4063c2d5c4413c9455c329d44e674e 
FATA[0003] Failed to decrypt secret due to 
failed to retrieve decrypted secret from arn:aws:ssm:us-west-2:${ID}:parameter/test/aws due to ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
        status code: 400, request id: 5086558a-b8d6-4cd4-980b-2865c82e6571: ValidationException: Parameter name: can't be prefixed with "ssm" (case-insensitive). If formed as a path, it can consist of sub-paths divided by slash symbol; each sub-path can be formed as a mix of letters, numbers and the following 3 symbols .-_
        status code: 400, request id: 5086558a-b8d6-4cd4-980b-2865c82e6571 

```

**Comment by bvtujo** [comment] 2020-04-14 18:37
Thanks for reaching out with this! We'll take a look and try to get a fix out shortly. Is there any chance you could share an (anonymized) code snippet of your use case?

**Comment by Aubtin** [comment] 2020-04-14 19:29
I found that it isn't actually "aws" or "ssm" which is causing the error, but it seems to error if the name is any deeper than 1 level in the hierarchy. 

Here is some sample Terraform code similar to what is used for the task definition I'm trying to run locally along with the SSM parameter:

Task Definition:
```
resource "aws_ecs_task_definition" "my_task_definition" {
  family = "MyTaskDefinition-${var.stage}"
  execution_role_arn = data.aws_iam_role.execution_role.arn
  task_role_arn = data.aws_iam_role.task_role.arn
  requires_compatibilities = ["FARGATE"]
  cpu = 256
  memory = 1024
  network_mode = "awsvpc"

  container_definitions = jsonencode([
    {
      name = "MyTaskDefinition"
      image = "${data.aws_ecr_repository.mytaskdefinition.repository_url}:${var.stage == "production" ? "production" : "latest"}"
      logConfiguration: {
        logDriver: "awslogs",
        secretOptions: null,
        options: {
          "awslogs-group": "/ecs/MyTaskDefinition-${var.stage}",
          "awslogs-region": "us-west-2",
          "awslogs-stream-prefix": "ecs"
        }
      },
      secrets = [
        {
          name = "TEST"
          valueFrom = aws_ssm_parameter.test.arn
        }
      ]
    }
  ])
}
```

SSM Parameter:
```
resource "aws_ssm_parameter" "test" {
  name = "/test/aws"
  type = "String"
  value = "TEST-TEST"
}
```

When the SSM Parameter is changed to the following, the error no longer occurs (just the top-level):
```
resource "aws_ssm_parameter" "test" {
  name = "/test"
  type = "String"
  value = "TEST-TEST"
}
```

The default docker-compose files are used from the command I outlined.

**Comment by bvtujo** [comment] 2020-04-14 20:47
Hey, it looks like this is due to the way that SSM parses parameter names inside of hierarchies. 

The [documentation](https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-parameter-name-constraints.html) for parameter names says that parameter names can't be prefixed with "aws." This is confusing, though, because it seems like that should allow your first case ("/test/aws") to work. 

The problem arises with how SSM parses hierarchies. Basically, forward slashes in parameter names designate a new level of parameter hierarchy, with the param name as SSM sees it only starting *after* the final forward slash in the name. 

So in your "/test/aws" example, SSM considers "aws" to be the param name. That's why "/test" works fine. I think according to these rules, the parameter "/test/param-aws" would work, as would "/test-aws". 

Does that make sense? I'm going to close this for now but feel free to reopen if this didn't solve your problem!

**Closed by bvtujo** 2020-04-14 20:47 UTC
Labels: Investigating, bug, ecs-local

**Comment by Aubtin** [comment] 2020-04-14 20:51
Seems like it is related to the hierarchies that are longer than the root, as this below also causes the same error: 

```
resource "aws_ssm_parameter" "test" {
  name = "/test/test2/test3"
  type = "String"
  value = "TEST-TEST"
}
```

**Comment by bvtujo** [comment] 2020-04-15 21:23
On further investigation, this was caused by the CLI incorrectly parsing nested paths from parameters specified by ARN. The AWS SDK throws an error if a parameter name containing a hierarchy does not have a leading `/`, and when we parsed parameter names from ARNs we would always drop the leading slash, even if they contained a hierarchy.

This led to this issue, and the issue described in #1011, where it appeared that parameters containing a hierarchy would always fail to be pulled from SSM.
