### ISSUE TITLE
compose different environments

### ISSUE THREAD

**Issue by esetnik** [aws/amazon-ecs-cli#57] opened 2016-01-06 06:50 UTC
`docker-compose` expose the `-f` switch to load one or more docker-compose override files. Is there something similar for ecs-cli?

**Comment by floostmodern** [comment] 2016-08-03 12:32
It seems to me that #129 is a duplicate of this. It would be really great to make `ecs-cli` support multiple `-f`.

In the meantime, there is a workaround : `docker-compose` has a validation command that shows the yaml files' concatenation in the console :

`docker-compose -f docker-compose.file1.yml -f docker-compose.file2.yml config` will output the concatenation of ` docker-compose.file1.yml` and `docker-compose.file2.yml`.

**Comment by chrisckc** [comment] 2017-03-01 17:56
Hi, I have just started using AWS for running docker and this is the first issue i encountered, is there any update on this?
The workaround suggested by @floostmodern is good and can be put in a bash script to capture the output to a new file and execute the  ecs-cli command with that file, but it would be better if the workaround was not required.
Thanks

**Comment by PeterRJones** [comment] 2017-03-11 01:41
While it is true that `docker-compose -f docker-compose.file1.yml -f docker-compose.file2.yml config` will output the merged config for all the given override files, the resulting file: 
- is not valid YAML
- is not valid docker-compose format
- is not consumable by ecs-cli
- requires additional touch-ups before it can be successfully to `ecs-cli`

I don't really see this as a valid work-around for this. If this feature is not to be supported, it would be *helpful* to show an error when ecs-cli is run with this type of syntax (today this is allowed, seems to work but silently fails):

**Comment by jdno** [comment] 2017-03-13 08:59
We require this functionality as well to set a few environment/stage/cluster specific options for our containers. While we could potentially configure them with environment variables as well, it is much more inline with our development workflow to merge and overwrite them using different files.

We normally run services like this:
    $ docker-compose -f service.yml -f stage.yml up/run

While the workaround by @floostmodern works for now, it would be great if `ecs-cli` supported this functionality natively. Who knows if `docker-compose config` will work forever...

**Comment by AlJohri** [comment] 2017-03-30 19:45
Building on what @floostmodern said, this works for me temporarily.

Full Command:
```bash
docker-compose -f docker-compose.yml -f docker-compose.production.yml config | sed "s/version: '2.0'/version: 2/" | ecs-cli compose --verbose --file /dev/stdin create
```

I tend to shorten it like so:
```bash
alias docker-compose-prod='docker-compose -f docker-compose.yml -f docker-compose.production.yml'
alias docker-compose-prod-config="docker-compose-prod config | sed \"s/version: '2.0'/version: 2/\""
alias ecs-cli-prod="docker-compose-prod-config | ecs-cli compose --file /dev/stdin"
```

```bash
ecs-cli-prod create
```

**Closed** 2017-06-28 20:01 UTC
Labels: Feature request

**Comment by yinshiua** [comment] 2017-06-28 20:06
You can now run `ecs-cli compose up` with multiple compose files with the latest commit. This will be included in the next release.

**Comment by timwah** [comment] 2017-07-11 17:34
@yinshiua Great! When is the next release is scheduled?

**Comment by jfroom** [comment] 2017-09-13 23:18
Looks like it was included in this release according to the release notes:
https://github.com/aws/amazon-ecs-cli/releases/tag/v0.6.1

**Comment by rogersgt** [comment] 2017-10-05 14:35
I am still having this issue in v0.6.5... Is there any update on this? Was this feature removed after v0.6.1?

**Comment by logemann** [comment] 2018-09-15 11:30
this doesnt work for me with latest client:
ecs-cli compose --file docker-compose.yml --file docker-compose-aws.yml service up

so how to define multiple files? the overridden settings in my second file wont get picked up.

**Comment by esetnik** [comment] 2018-09-15 14:44
@logemann Are you sure you are using the latest ecs-cli? The above example does work for me. If you run with —debug what task definition does it spit out?
