### ISSUE TITLE
Using assume role with ecs-cli version 1.0.0

### ISSUE THREAD

**Issue by mattmccarty** [aws/amazon-ecs-cli#369] opened 2017-11-09 17:16 UTC
In AWS/ECS our development/testing and production environments reside in the same region. In order to update any AWS/ECS resources in the development/testing "account", we have to login with our normal credentials and assume the role "DevelopmentTeam". The same goes for production, though the assumed role is "ProductionTeam".

Recently, we decided to upgrade to ecs-cli version 1.0.0. I noticed that I cannot use the --aws-profile parameter [documented here](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/ECS_CLI_migrating_config_files.html)  to assume a role. When attempting to upload a new task, it gets uploaded, but not under the assumed role in the config file ~/.aws/config.

Here are my current aws and ecs-cli configuration files:

**Versions**
```
aws-cli/1.11.184 Python/2.7.13 Linux/4.13.9-200.fc26.x86_64 botocore/1.7.42
ecs-cli version 1.0.0 (bda91d5)
```

**~/.aws/credentials**
```
[default]
aws_access_key_id     = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = SXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[production]
aws_access_key_id     = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = SXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

**~/.aws/config**
```
[default]
role_arn       = arn:aws:iam::XXXXXXXXXXXX:role/DevelopmentTeam
source_profile = default
region         = us-east-1
output         = json

[profile production]
role_arn       = arn:aws:iam::ZZZZZZZZZZZZ:role/ProductionTeam
source_profile = production
region         = us-east-1
output         = json
```

**~/.ecs/config**
```
version: v1
default: dev-application
clusters:
  dev-application:
    cluster: dev-application
    region: us-east-1
  prod-application:
    cluster: prod-application
    region: us-east-1
```

**Example Command**
```
ecs-cli compose -p dev-application -f /path/to/compose/file -c dev-application --cluster-config dev-application --aws-profile default create
```

Is this a bug, or are we doing this wrong?

**Comment by yegeniy** [comment] 2017-11-09 23:10
> SharedCredsAccessKey: shared credentials foo in ~/.aws/credentials did not contain aws_access_key_id
caused by: error when getting key of section 'foo': key 'aws_access_key_id' not exists"

```
[default]
aws_access_key_id = ...
aws_secret_access_key = ...

[foo]
role_arn = arn:aws:iam::1234567890:role/my_TeamRole
source_profile = default
```

**Comment by PettitWesley** [comment] 2017-11-10 09:18
@mattmccarty @yegeniy, please see the example that we have for assuming a role using an AWS Profile in the code [here](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/config/aws_credentials_example.ini). We have a test case which tests this [here](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/config/config_test.go#L331).

Here is the example:

```
[assumeRoleWithCreds]
role_arn = assumeRoleWithCredsRoleArn
source_profile = assumeRoleWithCreds
external_id = 1234
role_session_name = assumeRoleWithCredsSessionName
aws_access_key_id = assumeRoleWithCredsAKID
aws_secret_access_key = assumeRoleWithCredsSKID
```

Let us know if using this works! Also, apologies for the obscurity of this example, we will add a link to it in our README so that it is easier to find.

**Comment by mattmccarty** [comment] 2017-11-10 15:13
@PettitWesley I have updated my ~/.aws/credentials file as you requested.

```
[default]
role_arn              = arn:aws:iam::XXXXXXXXXXXX:role/DevelopmentTeam
source_profile        = default
role_session_name     = someSessionNameString
external_id           = someRandomString
aws_access_key_id     = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = SXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

[production]
role_arn              = arn:aws:iam::ZZZZZZZZZZZZ:role/ProductionTeam
source_profile        = production
role_session_name     = someSessionNameStringForProduction
external_id           = someRandomStringForProduction
aws_access_key_id     = XXXXXXXXXXXXXXXXXXXX
aws_secret_access_key = SXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```
The ecs-cli will still not assume the role specified in role_arn.

**Comment by PettitWesley** [comment] 2017-11-13 02:17
@mattmccarty I'm investigating; I'm trying to reproduce your issue- I will get back to you as soon as possible. 

I just want to confirm one thing- assume role used to work for you until your upgraded to `v1.0` of the ECS CLI, correct?

**Comment by mattmccarty** [comment] 2017-11-13 15:04
@PettitWesley it did work prior to version 1.0. I was using the --profile parameter instead of the --aws-profile parameter, however.

**Comment by PettitWesley** [comment] 2017-11-13 19:49
@mattmccarty, apologies, this looks like its probably a bug. I can put up a fix on GitHub quickly, but obviously it will take some time before this patch is released in our pre-built binaries (if you want the fix as soon as possible, you'll have to build from the source code). 

@mattmccarty, @yegeniy, in the mean time, here's a much better work around than I gave in my last message. If you look at [config_test.go#L336](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/config/config_test.go#L336), the test case that we have for assume role uses the `$AWS_DEFAULT_PROFILE` Env Var. Looking through [config_v1.go](https://github.com/aws/amazon-ecs-cli/blob/master/ecs-cli/modules/config/config_v1.go#L161), it looks like the bug is that we are only enabling `SharedConfigState` on the AWS Session object in the case where that Env Var is found. 

That means that assume role will only work if you specify AWS Profile name using `$AWS_DEFAULT_PROFILE`; whereas in all other cases it will simply pull the Credentials from the the profile, but will ignore the assume role information. 

I'll update in this issue once I've confirmed all of this, and submitted a fix. If you discover anything new, please post in this issue, to allow others to benefit as well. 

Also, the following information on the order of precedence will be useful (this is from #370):

1) ECS CLI Profile Flags
   a) ECS Profile (--ecs-profile)
   b) AWS Profile (--aws-profile)
 2) Environment Variables - attempts to fetch the credentials from environment variables:
   a) ECS_PROFILE
   b) AWS_PROFILE
   c) AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY, Optional: AWS_SESSION_TOKEN
 3) ECS Config - attempts to fetch the credentials from the default ECS Profile
 4) Default AWS Profile - attempts to use credentials (aws_access_key_id, aws_secret_access_key) or assume_role (role_arn, source_profile) from AWS profile name
   a) AWS_DEFAULT_PROFILE environment variable (defaults to 'default')
 5) EC2 Instance role

As you can see, `$AWS_DEFAULT_PROFILE` has the lower precedence than the default ECS Profile.

**Comment by yegeniy** [comment] 2017-11-14 05:19
Thank you for the details Wesley. This makes sense now.

**Comment by mattmccarty** [comment] 2017-11-14 16:03
Thanks for the info @PettitWesley !

**Comment by yegeniy** [comment] 2017-11-20 18:30
This workaround worked for me. Note that, due order of precedence, you must _only_ have the `AWS_DEFAULT_PROFILE` parameter set. Not the `AWS_PROFILE` one

**Closed** 2017-11-29 21:43 UTC
Labels: Bug, Investigating, v.1.0

**Comment by dimisjim** [comment] 2019-03-08 14:09
@PettitWesley @yegeniy Have tried both:
`AWS_DEFAULT_PROFILE=AW_PROD_PHP  ecs-cli ps --cluster prodcution --region eu-west-1`
`ecs-cli ps --cluster prodcution --aws-profile AW_PROD_PHP --region eu-west-1`


but getting: 

> Error executing 'ps': AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.

**Comment by yegeniy** [comment] 2019-03-08 20:58
Hey @dimisjim, I haven't really used this tool for about a year, so I don't think I can help you debug it at this time. 

I recommend eliminating the possibility that you are not providing your credentials correctly first.

& Ensure you can do whatever the `ecs-cli ps` command does without using `ecs-cli` to start, while using that `AW_PROD_PHP` user.
* I don't believe that I was trying to assume role with MFA enabled, but maybe I was... Is the presence of `AssumeRoleTokenProviderNotSetError` telling you that you are doing something different from what you were expecting to be doing?

It looks like this project is on version `1.13.0` by this point, though, so after debugging your approach as far as you can / have time for, you may want to consider opening a new issue and linking to this one if no one responds in a timely manner.

**Comment by PettitWesley** [comment] 2019-03-09 00:28
@dimisjim I think you're getting that error because the CLI doesn't support prompting for an MFA token (we need to add this).

Right now, the best way to use MFA with the CLI is to call assume-role with the AWS CLI, and then configure an ECS CLI Profile with the resulting access key, secret key, and session token:

```
ecs-cli configure profile --profile-name profile_name --access-key <value> --secret-key <value> --session-token <value>
```

If anyone wants to try to add support for this in the ECS CLI, I believe that [this SDK Package](https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/) could be used to add this functionality. Hopefully we'll be able to work on this eventually.

**Comment by dimisjim** [comment] 2019-03-09 13:28
@PettitWesley Thanks for the reply. Hopefully this is gonna get added soon.

**Comment by envision** [comment] 2019-04-28 22:09
Getting same error than @dimisjim.

**Comment by envision** [comment] 2019-04-28 22:15
Cannot even use this approach for getting session token: `aws sts get-session-token --profile myprofilename`

`An error occurred (AccessDenied) when calling the GetSessionToken operation: Cannot call GetSessionToken with session credentials`

**Comment by PettitWesley** [comment] 2019-04-29 01:19
@envision If your profile is already based on temporary credentials, you can not call GetSessionToken again: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html#stsapi_comparison
