### ISSUE TITLE
support enabling the autoscaling of the container through ecs-cli

### ISSUE THREAD

**Issue by Mehul1313** [aws/amazon-ecs-cli#561] opened 2018-07-18 19:54 UTC
### Summary

Need an ability to enable the autoscaling (not desired count) when CPU/Mem resource hits the container resource limit.

### Config files

* docker-compose.yml

* ecs-params.yml

* ~/.ecs/config

**Comment by SoManyHs** [comment] 2018-07-24 18:36
This appears to be a duplicate of https://github.com/aws/amazon-ecs-cli/issues/205. Closing this issue to track there.

**Closed by SoManyHs** 2018-07-24 18:36 UTC
